export const USER_ACTIONS = {
    FETCH_USER_PROFILE_REQUEST: 'FETCH_USER_PROFILE_REQUEST',
    FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
    FETCH_USER_PROFILE_FAILURE: 'FETCH_USER_PROFILE_FAILURE'
}

export const fetchUserProfile = () => {
    return {
        type: USER_ACTIONS.FETCH_USER_PROFILE_REQUEST
    }
}
